# Generated by Django 3.2.15 on 2022-08-05 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_invoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='request',
            field=models.OneToOneField(limit_choices_to={'status': 3}, on_delete=django.db.models.deletion.CASCADE, to='api.request'),
        ),
    ]
