# Generated by Django 3.2.15 on 2022-08-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_invoice_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No'), (2, 'Yes')], default=1),
        ),
    ]
